### PR TITLE
fix compile with Qt 6.9.0 - qplatformnativeinterface.h missing

### PR DESCRIPTION
**Pull request by FelixBer**
This was previously handled here:

if (UNIX AND NOT APPLE)
    include_directories(${Qt${QT_VERSION_MAJOR}Gui_PRIVATE_INCLUDE_DIRS})
endif()

but it seems Qt is phasing this out in favor of explicit cmake targets added in Qt 6.

btw, my Ubunut 22.04 also needed the following libs after upgrading from 6.7.2:
sudo apt install libxkbcommon-dev libxkbfile-dev libxcb-xkb-dev

### CODE REVIEW

**Comment by n-elie** [comment]
Hello,

I am trying to build `Qt-Advanced-Docking-System 4.4.1` on [conda-forge](https://github.com/conda-forge/qt6-advanced-docking-system-feedstock/pull/22) and I am facing an issue related to `qplatformnativeinterface.h` with `Qt5` on `Linux`
Is this fix also needed for Qt5?

```
2025-08-22T11:48:48.3186906Z /home/conda/feedstock_root/build_artifacts/qt5-advanced-docking-system_1755863155464/work/src/ads_globals.cpp:45:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
2025-08-22T11:48:48.3188682Z    45 | #include <qpa/qplatformnativeinterface.h>
2025-08-22T11:48:48.3191326Z       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-08-22T11:48:48.3193624Z compilation terminated.
```
