### ISSUE TITLE
Visual differences in static linking

### ISSUE THREAD

**Issue by naggerx** [githubuser0xFFFF/Qt-Advanced-Docking-System#149]
I'm using Windows10. I noticed that the tabs are looking kind of ugly when static linking of ADS is activated:
![ads_static](https://user-images.githubusercontent.com/64040582/79802572-7cac7f00-8360-11ea-9569-d1ff2feeada3.png)
(build with VS2017 x64, Qt5.12.4, CMake)

**Comment by naggerx** [comment]
Resolved this by myself. 
The resources of ADS are not loaded automatically when linked statically.
See: https://doc.qt.io/qt-5/resources.html#using-resources-in-a-library
When I add `Q_INIT_RESOURCE(ads);` in main() everythink works properly.

Maybe you could add this line to ./example/main.cpp or as stated in the qt-doc "close to where the resources are used in your library"

**Comment by githubuser0xFFFF** [comment]
Thank you for the report. If I follow your proposal and do this:

```c++
//============================================================================
void DockManagerPrivate::loadStylesheet()
{
	Q_INIT_RESOURCE(ads);
	QString Result;
#ifdef Q_OS_LINUX
    QFile StyleSheetFile(":ads/stylesheets/default_linux.css");
#else
	QFile StyleSheetFile(":ads/stylesheets/default.css");
#endif
	StyleSheetFile.open(QIODevice::ReadOnly);
	QTextStream StyleSheetStream(&StyleSheetFile);
	Result = StyleSheetStream.readAll();
	StyleSheetFile.close();
	_this->setStyleSheet(Result);
}

I get the following linker error:

```

```
QtAdvancedDockingSystem\ build\src/../../src/DockManager.cpp:150: undefined reference to `ads::qInitResources_ads()'
```
Do you have an idea how to fix this? Or could you provide a workinf pull request?

**Comment by naggerx** [comment]
> I get the following linker error:
> QtAdvancedDockingSystem\ build\src/../../src/DockManager.cpp:150: undefined reference to `ads::qInitResources_ads()'

Your patch works for me on VS2017...


After a lot of testing (and new insights to c++) there are compiler inconsistencies.
In VS2017 your patch works, because `Q_INIT_RESOURCE` declares `qInitResources_ads` without namespace. In GCC it doesn't work, because namespace "ads::" is added.
QT-docs also states: 
> Note: As the resource initializers generated by rcc are declared in the global namespace, your calls to Q_INIT_RESOURCE() also need to be done outside of any namespace.

If you disassemble the Macro Q_INIT_RESOURCE into its two parts it is working for me in gcc and VC2017:
```
+++ b/src/DockManager.cpp
@@ -55,6 +55,7 @@
 #include "DockingStateReader.h"


+extern int QT_MANGLE_NAMESPACE(qInitResources_ads) ();

 namespace ads
 {
@@ -148,6 +149,9 @@ DockManagerPrivate::DockManagerPrivate(CDockManager* _public) :
 //============================================================================
 void DockManagerPrivate::loadStylesheet()
 {
+    //Q_INIT_RESOURCE(ads); // does not work in gcc, because of namespace ads -> Macro resolved and divided
+    QT_MANGLE_NAMESPACE(qInitResources_ads) ();
```

But this depends on internal QT implementation :(

So my proposal is to add the Q_INIT_RESOURCE macro to main() of the example and demo and maybe document it in the readme.md.

**Comment by githubuser0xFFFF** [comment]
Hi, thank you for your detailed information. I just added a comit (85626c9a2133546f2371dc5a28331915d2daeb8f) to master that should fix this. I have put the Q_INIT_RESOURCE(ads) macro into a function in DockManager that is outside of the ads namespace. That fixed the linker error.

Please test, if this works for you.
